dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  fast_finish: false

install:
  - pip install --upgrade -r requirements-dev.txt
  - pip install .

script:
  - pytest --cov

after_success:
  - codecov -X gcov
