dist: xenial

cache:
  directories:
    - $HOME/.cache/pre-commit

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python -m pip install pre-commit
  - pre-commit run --all-files

install:
  - pip install --upgrade -r requirements-dev.txt
  - pip install .

script:
  - pytest --cov --durations=20

after_success:
  - codecov -X gcov
