os: linux

language: python
python:
  - "3.6"
  - "3.7"
env:
  - HTCONDOR_VERSION=8.8
  - HTCONDOR_VERSION=8.9

jobs:
  fast_finish: true

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install --upgrade htcondor==${HTCONDOR_VERSION}.*

script:
  - pytest

after_success:
  - codecov
