codecov:
  strict_yaml_branch: master
  token: 89120b28-41f0-4f87-bef9-400d269784b1
coverage:
  range: 50..100
  round: down
  precision: 0
  status:
    project:
      default:
        target: auto
        threshold: 5
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 20
        only_pulls: true
comment:
  layout: "diff, files"
  require_changes: false
