name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        htcondor-version: [8.8, 8.9]
        exclude:
          - htcondor-version: 8.8
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: pip install .[tests] htcondor==${{ matrix.htcondor-version }}.*
      - name: Run tests
        run: pytest --cov --durations=20
